### ISSUE TITLE
the password about emotionNet dataset

### ISSUE THREAD

**Issue by sohey1910** [hao-qiang/GANimation-tf#2]
Hi,hao-qiang
thanks for your works,have you got the password about emotionet dataset?

**Comment by c1a1o1** [comment]
Can you share the password for Me?
My email is cao2016@bupt.edu.cn.

**Comment by bsmith0003** [comment]
@hao-qiang, @sohey1910, @c1a101, you'r searching pass because you have zipped data?

**Comment by hao-qiang** [comment]
Sorry, I could not share the dataset due to copyright, but you can apply it using education mail.
