### ISSUE TITLE
emotionnet

### ISSUE THREAD

**Issue by YisuZhou** [hao-qiang/GANimation-tf#3]
哈喽～
我想请问一下您的数据集怎么下载的呀？我填写了表格然后一直都在Your Request is Being Processed。。。如果可以的话能不能回复一下～谢谢！

1252059873@qq.com

**Comment by xijunjun** [comment]
@YisuZhou 哈喽，数据集你下载到了吗？

**Comment by hao-qiang** [comment]
数据集申请时间会比较久。
